/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula_13_03_23;

import javax.swing.JOptionPane;

/**
 *
 * @author LABORATÓRIO
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setSize(450, 500);
        setTitle("Clientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeTexto = new javax.swing.JTextField();
        cpfTexto = new javax.swing.JTextField();
        emailTexto = new javax.swing.JTextField();
        telefoneTexto = new javax.swing.JTextField();
        nomeVisualizacao = new javax.swing.JLabel();
        CpfVisualizacao = new javax.swing.JLabel();
        emailVisualizacao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        telefoneVisualizacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 200, 16);

        jLabel2.setText("Cpf");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 200, 16);

        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 200, 16);

        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 200, 16);

        nomeTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextoFocusLost(evt);
            }
        });
        nomeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextoActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTexto);
        nomeTexto.setBounds(20, 50, 200, 22);

        cpfTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfTextoFocusLost(evt);
            }
        });
        getContentPane().add(cpfTexto);
        cpfTexto.setBounds(20, 110, 200, 22);

        emailTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextoFocusLost(evt);
            }
        });
        emailTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextoActionPerformed(evt);
            }
        });
        getContentPane().add(emailTexto);
        emailTexto.setBounds(20, 180, 200, 22);

        telefoneTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneTextoFocusLost(evt);
            }
        });
        getContentPane().add(telefoneTexto);
        telefoneTexto.setBounds(20, 240, 200, 22);

        nomeVisualizacao.setText("Nome");
        getContentPane().add(nomeVisualizacao);
        nomeVisualizacao.setBounds(20, 290, 200, 16);

        CpfVisualizacao.setText("CPF");
        getContentPane().add(CpfVisualizacao);
        CpfVisualizacao.setBounds(20, 330, 200, 16);

        emailVisualizacao.setText("Email");
        getContentPane().add(emailVisualizacao);
        emailVisualizacao.setBounds(20, 370, 200, 16);

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 320, 72, 22);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 320, 72, 22);

        telefoneVisualizacao.setText("Telefone");
        getContentPane().add(telefoneVisualizacao);
        telefoneVisualizacao.setBounds(20, 410, 200, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextoActionPerformed

    private void emailTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextoActionPerformed

    private void nomeTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextoFocusLost

        nomeVisualizacao.setText(nomeTexto.getText().trim());
    }//GEN-LAST:event_nomeTextoFocusLost

    private void cpfTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextoFocusLost
        CpfVisualizacao.setText(cpfTexto.getText().trim());
    }//GEN-LAST:event_cpfTextoFocusLost

    private void emailTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextoFocusLost
        emailVisualizacao.setText(emailTexto.getText().trim());
    }//GEN-LAST:event_emailTextoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Dados Cadastrados com Sucesso");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void telefoneTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneTextoFocusLost
          telefoneVisualizacao.setText(telefoneTexto.getText().trim());
    }//GEN-LAST:event_telefoneTextoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CpfVisualizacao;
    private javax.swing.JTextField cpfTexto;
    private javax.swing.JTextField emailTexto;
    private javax.swing.JLabel emailVisualizacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeTexto;
    private javax.swing.JLabel nomeVisualizacao;
    private javax.swing.JTextField telefoneTexto;
    private javax.swing.JLabel telefoneVisualizacao;
    // End of variables declaration//GEN-END:variables
}
